export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';

export const USERS_SHOULD_FETCH = 'USERS_SHOULD_FETCH';
export const USERS_FULFILLED = 'USERS_FULFILLED';
export const USERS_PENDING = 'USERS_PENDING';
export const USERS_REJECTED = 'USERS_REJECTED';

export const POSTS_SHOULD_FETCH = 'POSTS_SHOULD_FETCH';
export const POSTS_FULFILLED = 'POSTS_FULFILLED';
export const POSTS_PENDING = 'POSTS_PENDING';
export const POSTS_REJECTED = 'POSTS_REJECTED';

export const DETAILS_FULFILLED = 'DETAILS_FULFILLED';
export const DETAILS_PENDING = 'DETAILS_PENDING';
export const DETAILS_REJECTED = 'DETAILS_REJECTED';

export const USERPOSTS_FULFILLED = 'USERPOSTS_FULFILLED';
export const USERPOSTS_PENDING = 'USERPOSTS_PENDING';
export const USERPOSTS_REJECTED = 'USERPOSTS_REJECTED';
